package com.ebillity.core.model.dto
{

	public class ExpenseEntryDTO
	{
		public var classId:int;

		public var clientId:int;

		public var cost:int;

		public var description:String;

		public var employeeId:int;

		public var expenseEntryDate:String;

		public var expenseEntryDateEpoc:String;

		public var expenseId:int;

		public var expenseTypeId:int;

		public var expenseTypeName:String;

		public var filePath:String;

		public var firmId:int;

		public var insertedBy:int;

		public var isApproved:Boolean;

		public var isAutoGenerated:Boolean;

		public var isBillable:Boolean;

		public var isFinalized:Boolean;

		public var isPending:Boolean;

		public var isRejected:Boolean;

		public var isSubmitted:Boolean;

		public var markupRatio:int;

		public var projectId:int;

		public var projectName:String;

		public var quantity:int;

		public var reimburse:Boolean;

		public var tax:int;

		public var taxable:Boolean;

		public var totalCost:int;

		public var updatedBy:int;

		public var userId:int;

		public var userName:String;
	}
}
