package com.ebillity.core.model.dto
{

	public class TimeEntryDTO
	{

		public var aBACodeId:int;

		public var activityName:String;

		public var applicationId:String;

		public var awardAmount:int;

		public var billableType_Id:int;

		public var classId:int;

		public var clientName:String;

		public var client_Id:int;

		public var contingency:int;

		public var contingencyAmount:int;

		public var elapsedHour:int;

		public var elapsedMinute:int;

		public var employeeFirstName:String;

		public var employeeId:int;

		public var employeeLastName:String;

		public var employeeType:String;

		public var entryId:String;

		public var entryNumber:String;

		public var excludeFromInvoice:Boolean;

		public var filePath:String;

		public var firmBillableActivityType_Id:int;

		public var firm_Id:int;

		public var flatFeeAmount:int;

		public var fromHour:String;

		public var fromMinute:String;

		public var iPPPayrollId:String;

		public var insertedBy:int;

		public var internalDescription:String;

		public var invoiceDescription:String;

		public var isActive:Boolean;

		public var isAutoGenerated:Boolean;

		public var isBasic:Boolean;

		public var isBillable:Boolean;

		public var isFinalised:Boolean;

		public var isInvoiced:Boolean;

		public var isLastNameFirst:Boolean;

		public var isOverTime:Boolean;

		public var isOverrideTotalTime:Boolean;

		public var isSynchronized:Boolean;

		public var isVerifyTimeEntry:Boolean;

		public var isoverrideRate:Boolean;

		public var laborHour:int;

		public var laborMinute:int;

		public var overrideRate:int;

		public var overrideTotalHour:int;

		public var overrideTotalMinute:int;

		public var overrideTotalTimeComments:String;

		public var prePaidHours:int;

		public var projectName:String;

		public var project_Id:int;

		public var rate:int;

		public var scheduleId:int;

		public var showLitigation:Boolean;

		public var taskName:String;

		public var timeEntryDate:String;

		public var timeEntryDateEpoc:String;

		public var timeEntryId:int; //0 = Insert; anything else = update

		public var timeEntrySource:String;

		public var timeEntryStatusId:int;

		public var timeEntryType:Boolean;

		public var timeTrackRowNo:int;

		public var toHour:String;

		public var toMinute:String;

		public var totalHour:int;

		public var totalMinute:int;

		public var travelHour:int;

		public var travelMinute:int;

		public var updatedBy:int;

		public var usePrepaidHours:Boolean;

		public var user_Id:int;
	}
}
